### PR TITLE
Update to v4r 1.4.9

### PR DESCRIPTION
**Pull request by jibweb**
@bajo @edith-langer 
Here is the pull request to prepare for the update to v4r 1.4.9
squirrel_segmentation and 2d_recognition should work with then new v4r. @ToMadoRe the 3d recognizer wrapper is still not working with some "v4r::ObjectHypothesis is not a template" problem. It seems you updated the v4r_ros_wrappers accordingly, should we completely switch to those, and get rid of the squirrel specific wrappers for the 3d recognizer ?

I also updated the setup.sh script to the new repo ( @bajo , could you check that ? )

### CODE REVIEW

**Comment by ToMadoRe** [comment]
> It seems you updated the v4r_ros_wrappers accordingly, should we completely switch to those, and get rid of the squirrel specific wrappers for the 3d recognizer ?

Yes! Or is there any reason why this repo contains duplicated code of `v4r_ros_wrappers`?

**Comment by jibweb** [comment]
Not any I'm aware of. As far as I can remember, the messages definitions are slightly different (missing or added -s at the end) but semantically identical. One problem is that the up-to-date `v4r_ros_wrappers` are not yet available in our repositories (we still rely on strands repo for now)

**Comment by mzillich** [comment]
Let's use that opportunity to finally go to v4r ros_wrappers now. Just git clone it. No need for debian packages right now.

**Comment by bajo** [comment]
@ipa-nhg Do we need some changes in travis and buildbot to use V4R's apt repository as shown in this pr? The pr itself looks good to me, but fails because of the old version of v4r.

**Comment by jibweb** [comment]
Right now, the pr would still fail because of squirrel_recognition 3D recognizer wrappers ...

**Comment by ipa-nhg** [comment]
@jibweb please merge https://github.com/jibweb/squirrel_perception/pull/1 
I also updated the buildbot configuration https://github.com/buildbot-squirrel/rosdistro-squirrel/commit/43c966b16ea332d342e07baef2b5335b3be871f9 I will restart the server and trigger the build again

**Comment by ipa-nhg** [comment]
I am getting the following error with both CIs:

```
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
```

@bajo @jibweb ideas?

**Comment by bajo** [comment]
This package is usually not installed on Docker containers. But it is needed as our repo is provided via https. Just install it and it works. In had the same issue on our internal CI.

**Comment by ipa-nhg** [comment]
I copied the deb package to my mirror server and still not working https://travis-ci.org/squirrel-project/squirrel_perception/builds/281175995?utm_source=github_status&utm_medium=notification although Travis found and installed the package. I think it is the right version http://153.97.4.193/building/ubuntu/dists/trusty/main/binary-amd64/Packages (the last one)

**Comment by bajo** [comment]
@ipa-nhg Seems like @jibweb is aware of this bug and fixing it right now.

**Comment by ipa-nhg** [comment]
Thanks! buildbot is happy and travis is failing because the known timeout issue --> merge!

**Pull request merged**
