### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@bajo Is the lcas.lincoln.ac.uk server down?

I am geting  this error with travis:
```

executing command [sudo -H apt-get install -y -qq ros-indigo-classifier-srv-definitions]

E: Unable to correct problems, you have held broken packages.

ERROR: the following rosdeps failed to install

  apt: command [sudo -H apt-get install -y -qq ros-indigo-classifier-srv-definitions] failed

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Function rosdep_install returned with code '1' after 0 min 0 sec 
```

**Comment by ipa-nhg** [comment]
@bajo I think that something with the .deb package generation was wrong , I tried locally and said:
```
The following packages have unmet dependencies:
 ros-indigo-classifier-srv-definitions : Depends: ros-indigo-geometry-msgs but it is not going to be installed
                                         Depends: ros-indigo-message-runtime but it is not going to be installed
                                         Depends: ros-indigo-object-perception-msgs but it is not going to be installed
                                         Depends: ros-indigo-sensor-msgs but it is not going to be installed
                                         Depends: ros-indigo-std-msgs but it is not going to be installed
E: Unable to correct problems, you have held broken packages
```

**Comment by bajo** [comment]
@ipa-nhg http://lcas.lincoln.ac.uk/repos/release/pool/main/r/ros-indigo-v4r/ seems to be reachable from my computer in Vienna. The package itself did not change since January 2016.

**Comment by ipa-nhg** [comment]
Thanks @bajo , yes something is wrong with travis, I will try with my own  build scripts, may this work.

Thanks for your help

**Comment by ipa-nhg** [comment]
Error found! will remove the branch and reopen a new pull request with a clean history

**Pull request closed without merging**
