### PR TITLE
reduce parallel jobs

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by bajo** [comment]
@ipa-nhg Not sure if `travis 30 nvm install` is the correct command. 
I guess we need to replace `nvm install` with our actual build command.

**Comment by bajo** [comment]
I find it hard to believe that this takes more than 20 minutes to compile. 
But can you try with a timeout of 60 minutes? Just to make sure this is the issue.

**Comment by ipa-nhg** [comment]
Now is green , I am not sure if it was just  good luck...
I suggest merge this, at least this configuration is better than the old one. And we will see what happens with next builds

**Comment by bajo** [comment]
Good idea. Thanks

**Pull request merged**
